# Generated by Django 3.2 on 2021-09-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='disponivel',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
