# Generated by Django 3.2.7 on 2021-09-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='disponivel',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Nao', 'Não')], default='Nao', max_length=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor',
            field=models.FloatField(),
        ),
    ]
