# Generated by Django 3.2 on 2021-09-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_disponivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='disponivel',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10),
        ),
    ]
