# Generated by Django 3.2 on 2021-09-20 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produtos', '0002_produto_disponivel'),
        ('tecnicos', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servico',
            name='data_servico',
            field=models.DateField(auto_now=True, verbose_name='Data de Inicio'),
        ),
        migrations.AddField(
            model_name='servico',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='produto', to='produtos.produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servico',
            name='status',
            field=models.CharField(choices=[('nao_finalizado', 'Não Finalizado'), ('finalizado', 'Finalizado')], default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servico',
            name='tecnico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tecnico', to='tecnicos.tecnico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servico',
            name='tipo_servico',
            field=models.CharField(choices=[('manutencao', 'Manutenção'), ('troca', 'Troca'), ('formatacao', 'Formatação'), ('backup', 'Backup')], default=1, max_length=25, verbose_name='Tipo de Serviço'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao_servico',
            field=models.TextField(verbose_name='Descrição do Serviço'),
        ),
    ]
