# Generated by Django 3.2 on 2021-09-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='tipo_servico',
            field=models.CharField(choices=[('manutenção', 'Manutenção'), ('troca', 'Troca'), ('formatação', 'Formatação'), ('backup', 'Backup')], default=1, max_length=25, verbose_name='Tipo de Serviço'),
            preserve_default=False,
        ),
    ]
