# Generated by Django 3.2.7 on 2021-09-26 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0004_auto_20210926_1549'),
        ('produtos', '0002_alter_produto_id'),
        ('accounts', '0002_alter_cliente_id'),
        ('servicos', '0002_alter_servico_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Valor do serviço R$'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servico',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valor total'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente', to='accounts.cliente'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produto', to='produtos.produto'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnico', to='tecnicos.tecnico'),
        ),
    ]
