# Generated by Django 3.2 on 2021-09-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_servico_tipo_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='descricao_servico',
            field=models.TextField(verbose_name='Descrição do Serviço'),
        ),
    ]
