# Generated by Django 3.2 on 2021-09-20 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210919_2340'),
        ('servicos', '0002_auto_20210919_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cliente', to='accounts.cliente'),
        ),
    ]
