# Generated by Django 3.2 on 2021-09-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_alter_servico_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='status',
            field=models.CharField(choices=[('Não finalizado', 'Não Finalizado'), ('Finalizado', 'Finalizado')], max_length=25),
        ),
        migrations.AlterField(
            model_name='servico',
            name='tipo_servico',
            field=models.CharField(choices=[('Manutenção', 'Manutenção'), ('Troca', 'Troca'), ('Formatacao', 'Formatação'), ('Backup', 'Backup')], max_length=25, verbose_name='Tipo de Serviço'),
        ),
    ]
