# Generated by Django 3.2.7 on 2021-09-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_auto_20210926_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='status',
            field=models.CharField(choices=[('Nao finalizado', 'Não Finalizado'), ('Finalizado', 'Finalizado')], default='Nao finalizado', max_length=25),
        ),
        migrations.AlterField(
            model_name='servico',
            name='tipo_servico',
            field=models.CharField(choices=[('Manutencao', 'Manutenção'), ('Troca', 'Troca'), ('Formatacao', 'Formatação'), ('Backup', 'Backup')], default='Manutencao', max_length=25, verbose_name='Tipo de Serviço'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='valor',
            field=models.FloatField(verbose_name='Valor do serviço R$'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='valor_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor total'),
        ),
    ]
