# Generated by Django 3.2.7 on 2021-09-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_auto_20210928_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='valor_total',
            field=models.FloatField(null=True, verbose_name='Valor total'),
        ),
    ]
