# Generated by Django 3.2.7 on 2021-09-28 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_alter_servico_valor_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='valor_total',
        ),
    ]
