# Generated by Django 3.2.7 on 2021-09-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0003_tecnico_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnico',
            name='ativo',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], max_length=100, verbose_name='Status do Tecnico'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do Tecnico'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='registro',
            field=models.CharField(max_length=20, verbose_name='Registro'),
        ),
    ]
