# Generated by Django 3.2.7 on 2021-09-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0004_auto_20210926_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnico',
            name='ativo',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=100, verbose_name='Status do Tecnico'),
        ),
    ]
